name: install
on:
  - push
  - pull_request
jobs:
  install:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # we support >= py37
          # but beancount trunk only support py>=39
          python-version: '3.9'
      # Install dependencies for the example importers
      - run: sudo apt install poppler-utils
      # There are no released packages for beancount v3. Install from Git
      - run: python -m pip install git+https://github.com/beancount/beancount#egg=beancount
      - run: python -m pip install .
      - name: Run smoke test
        run: |
          cd examples
          python import.py --help
      - name: Run example importers unit tests
        run: |
          cd examples
          python -m unittest
      - name: Run example importers tests
        run: |
          cd examples
          python importers/acme.py test tests/acme --verbose
          python importers/csvbank.py test tests/csvbank --verbose
          python importers/utrade.py test tests/utrade --verbose
      - name: Run example ledger.import
        run: |
          cd examples
          python import.py identify Downloads -v
          python import.py extract Downloads
          python import.py archive Downloads -n -o documents
