name: test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
        beancount:
          - '~=2.3.5'
          - '~=3.0.0'
          - '@git+https://github.com/beancount/beancount.git'
        exclude:
          # Beancount dev version requires Python 3.9+
          - beancount: '@git+https://github.com/beancount/beancount.git'
            python: '3.8'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install 'beancount ${{ matrix.beancount }}'
      - run: pip install -r requirements.txt pytest
      - run: python -m pytest beangulp

  examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: sudo apt-get install poppler-utils
      - run: pip install .
      - name: Run smoke test
        run: |
          cd examples
          python import.py --help
      - name: Run example importers unit tests
        run: |
          cd examples
          python -m unittest
      - name: Run example importers tests
        run: |
          cd examples
          python importers/acme.py test tests/acme --verbose
          python importers/csvbank.py test tests/csvbank --verbose
          python importers/ofx.py test tests/ofx --verbose
          python importers/utrade.py test tests/utrade --verbose
      - name: Run example ledger.import
        run: |
          cd examples
          python import.py identify Downloads -v
          python import.py extract Downloads
          python import.py archive Downloads -n -o documents
